name: Jungleparadise Production
on:
  push:
    branches: 
      - master


jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.jungleparadise.tf
      uses: appleboy/ssh-action@master
      with:
        host: www.jungleparadise.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www_jungle_paradise/
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/www2.jungleparadise.tf/https:\/\/jungleparadise.tf/g" config.toml
          bash build.sh
